# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QUICConnetionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('conn_id', models.CharField(max_length=16)),
                ('num_incoming_streams', models.IntegerField()),
                ('num_outgoing_streams', models.IntegerField()),
                ('max_path_id', models.IntegerField()),
                ('num_active_paths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QUICFlowControlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_conn_flow_control', models.BooleanField(default=False)),
                ('stream_id', models.BigIntegerField()),
                ('bytes_sent', models.BigIntegerField()),
                ('retransmitted_bytes', models.BigIntegerField()),
                ('sending_window', models.BigIntegerField()),
                ('last_window_update_time', models.DateTimeField()),
                ('bytes_read', models.BigIntegerField()),
                ('highest_received_byte', models.BigIntegerField()),
                ('receive_window', models.BigIntegerField()),
                ('receive_window_increment', models.BigIntegerField()),
                ('max_receive_window_increment', models.BigIntegerField()),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_controls', to='quicinfos.QUICConnetionInfo')),
            ],
        ),
        migrations.CreateModel(
            name='QUICPathInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField()),
                ('smoothed_rtt', models.DurationField()),
                ('last_activity_time', models.DateTimeField()),
                ('last_received_packet_number', models.BigIntegerField()),
                ('least_unacked_packet_number', models.BigIntegerField()),
                ('largest_acked_packet', models.BigIntegerField()),
                ('largest_received_packet_with_ack', models.BigIntegerField()),
                ('bytes_in_flight', models.BigIntegerField()),
                ('rto_count', models.IntegerField()),
                ('tlp_count', models.IntegerField()),
                ('last_lost_time', models.DateTimeField()),
                ('last_sent_time', models.DateTimeField()),
                ('sent_packets', models.BigIntegerField()),
                ('retransmissions', models.BigIntegerField()),
                ('losses', models.BigIntegerField()),
                ('largest_observed_packet_number', models.BigIntegerField()),
                ('lower_limit_packet_number', models.BigIntegerField()),
                ('largest_observed_receive_time', models.DateTimeField()),
                ('ack_send_delay', models.DurationField()),
                ('packets_received_since_last_ack', models.IntegerField()),
                ('retransmittable_packets_received_since_last_ack', models.IntegerField()),
                ('received_packets', models.BigIntegerField()),
                ('congestion_window', models.BigIntegerField()),
                ('local_port', models.PositiveIntegerField()),
                ('local_ip', models.GenericIPAddressField()),
                ('remote_port', models.PositiveIntegerField()),
                ('remote_ip', models.GenericIPAddressField()),
                ('rto_timeout', models.DurationField()),
                ('interface_name', models.CharField(max_length=10)),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='quicinfos.QUICConnetionInfo')),
            ],
        ),
        migrations.CreateModel(
            name='QUICTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='quicconnetioninfo',
            name='test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conns', to='quicinfos.QUICTestInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='quicpathinfo',
            unique_together=set([('conn', 'path_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='quicflowcontrolinfo',
            unique_together=set([('conn', 'is_conn_flow_control', 'stream_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='quicconnetioninfo',
            unique_together=set([('test_info', 'time', 'conn_id')]),
        ),
    ]
