# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicinfos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicpathinfo',
            name='ack_send_delay',
        ),
        migrations.RemoveField(
            model_name='quicpathinfo',
            name='rto_timeout',
        ),
        migrations.RemoveField(
            model_name='quicpathinfo',
            name='smoothed_rtt',
        ),
    ]
