# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicinfos', '0003_auto_20180316_1324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quicflowcontrolinfo',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='quicpathinfo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quicflowcontrolinfo',
            name='stream_id',
        ),
        migrations.RemoveField(
            model_name='quicpathinfo',
            name='path_id',
        ),
    ]
