# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicinfos', '0004_auto_20180316_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicflowcontrolinfo',
            name='stream_id',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quicpathinfo',
            name='path_id',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quicflowcontrolinfo',
            unique_together=set([('conn', 'is_conn_flow_control', 'stream_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='quicpathinfo',
            unique_together=set([('conn', 'path_id')]),
        ),
    ]
