# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicinfos', '0005_auto_20180316_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicpathinfo',
            name='local_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicpathinfo',
            name='local_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicpathinfo',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicpathinfo',
            name='remote_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
