# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicinfos', '0006_auto_20180316_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QUICConnetionInfo',
            new_name='QUICConnectionInfo',
        ),
    ]
