# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectivityResult',
            new_name='ConnectivityOldResult',
        ),
    ]
