# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0004_auto_20180116_1535'),
        ('connectivity', '0003_auto_20180116_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectivitytest',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='connectivitytest',
            unique_together=set([('benchmark', 'order')]),
        ),
    ]
