# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0004_auto_20180116_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectivitytest',
            old_name='config',
            new_name='protocol',
        ),
    ]
