# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0005_auto_20180116_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivityconfig',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connectivity.ConnectivityTest'),
        ),
        migrations.AlterField(
            model_name='connectivityresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='connectivity.ConnectivityTest'),
        ),
    ]
