# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0009_connectivitytest_rcv_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectivityconfig',
            name='test',
        ),
        migrations.AddField(
            model_name='connectivitytest',
            name='config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='connectivity.ConnectivityConfig'),
            preserve_default=False,
        ),
    ]
