# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0011_connectivityresult_error_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectivityDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.DurationField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='connectivity.ConnectivityResult')),
            ],
        ),
    ]
