# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0012_connectivitydelay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectivitydelay',
            name='delay',
        ),
        migrations.AddField(
            model_name='connectivitydelay',
            name='delay_ms',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
