# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0013_auto_20180207_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectivitydelay',
            old_name='delay_ms',
            new_name='delay',
        ),
    ]
