# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPTCPConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('conn_id', models.PositiveIntegerField()),
                ('rxbytes', models.BigIntegerField()),
                ('txbytes', models.BigIntegerField()),
                ('subflowcount', models.PositiveSmallIntegerField()),
                ('switchcount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MPTCPSubflowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subflow_id', models.PositiveSmallIntegerField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_ip', models.GenericIPAddressField()),
                ('interfaceindex', models.PositiveSmallIntegerField()),
                ('isexpensive', models.BooleanField()),
                ('rxbytes', models.BigIntegerField()),
                ('txbytes', models.BigIntegerField()),
                ('switches', models.PositiveSmallIntegerField()),
                ('tcp_last_outif', models.PositiveSmallIntegerField()),
                ('tcpi_cell_rxbytes', models.BigIntegerField()),
                ('tcpi_cell_rxpackets', models.BigIntegerField()),
                ('tcpi_cell_txbytes', models.BigIntegerField()),
                ('tcpi_cell_txpackets', models.BigIntegerField()),
                ('tcpi_flags', models.IntegerField()),
                ('tcpi_if_cell', models.BooleanField()),
                ('tcpi_if_wifi', models.BooleanField()),
                ('tcpi_if_wifi_awdl', models.BooleanField()),
                ('tcpi_if_wifi_infra', models.BooleanField()),
                ('tcpi_if_wired', models.BooleanField()),
                ('tcpi_options', models.PositiveSmallIntegerField()),
                ('tcpi_rcv_mss', models.PositiveIntegerField()),
                ('tcpi_rcv_nxt', models.IntegerField()),
                ('tcpi_rcv_space', models.IntegerField()),
                ('tcpi_rcv_wscale', models.PositiveSmallIntegerField()),
                ('tcpi_rto', models.IntegerField()),
                ('tcpi_rttbest', models.IntegerField()),
                ('tcpi_rttcur', models.IntegerField()),
                ('tcpi_rttvar', models.IntegerField()),
                ('tcpi_rxbytes', models.BigIntegerField()),
                ('tcpi_rxduplicatebytes', models.BigIntegerField()),
                ('tcpi_rxoutoforderbytes', models.BigIntegerField()),
                ('tcpi_rxpackets', models.BigIntegerField()),
                ('tcpi_snd_bw', models.BigIntegerField()),
                ('tcpi_snd_cwnd', models.IntegerField()),
                ('tcpi_snd_mss', models.IntegerField()),
                ('tcpi_snd_nxt', models.IntegerField()),
                ('tcpi_snd_sbbytes', models.IntegerField()),
                ('tcpi_snd_ssthresh', models.IntegerField()),
                ('tcpi_snd_wnd', models.IntegerField()),
                ('tcpi_snd_wscale', models.PositiveSmallIntegerField()),
                ('tcpi_srtt', models.IntegerField()),
                ('tcpi_state', models.PositiveSmallIntegerField()),
                ('tcpi_synrexmits', models.PositiveSmallIntegerField()),
                ('tcpi_txbytes', models.BigIntegerField()),
                ('tcpi_txpackets', models.BigIntegerField()),
                ('tcpi_txretransmitbytes', models.BigIntegerField()),
                ('tcpi_txretransmitpackets', models.BigIntegerField()),
                ('tcpi_txunacked', models.BigIntegerField()),
                ('tcpi_wifi_rxbytes', models.BigIntegerField()),
                ('tcpi_wifi_rxpackets', models.BigIntegerField()),
                ('tcpi_wifi_txbytes', models.BigIntegerField()),
                ('tcpi_wifi_txpackets', models.BigIntegerField()),
                ('tcpi_wired_rxbytes', models.BigIntegerField()),
                ('tcpi_wired_rxpackets', models.BigIntegerField()),
                ('tcpi_wired_txbytes', models.BigIntegerField()),
                ('tcpi_wired_txpackets', models.BigIntegerField()),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subflows', to='mptcpinfos.MPTCPConnectionInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MPTCPTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='mptcpconnectioninfo',
            name='test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptcpinfos.MPTCPTestInfo'),
        ),
    ]
