# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptcpinfos', '0003_auto_20180316_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mptcpconnectioninfo',
            name='test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conns', to='mptcpinfos.MPTCPTestInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='mptcpconnectioninfo',
            unique_together=set([('test_info', 'time', 'conn_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='mptcpsubflowinfo',
            unique_together=set([('conn', 'subflow_id')]),
        ),
    ]
