# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptcpinfos', '0004_auto_20180316_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mptcpsubflowinfo',
            name='dst_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mptcpsubflowinfo',
            name='src_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
