# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptcpinfos', '0005_auto_20180316_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mptcpsubflowinfo',
            old_name='tcp_last_outif',
            new_name='tcpi_last_outif',
        ),
    ]
