# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mptests', '0011_remove_benchmark_quic_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField()),
                ('upload_chunk_size', models.PositiveIntegerField()),
                ('download_chunk_size', models.PositiveIntegerField()),
                ('upload_interval_time', models.DurationField()),
                ('download_interval_time', models.DurationField()),
                ('duration', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('delay', models.DurationField()),
                ('upload', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('error_msg', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('wait_time', models.DurationField()),
                ('duration', models.DurationField()),
                ('protocol', models.CharField(max_length=20)),
                ('protocol_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rcv_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptests.Benchmark')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='stream.StreamConfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='streamresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='stream.StreamTest'),
        ),
        migrations.AddField(
            model_name='streamdelay',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='stream.StreamResult'),
        ),
        migrations.AlterUniqueTogether(
            name='streamtest',
            unique_together=set([('benchmark', 'order')]),
        ),
    ]
