# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0001_initial'),
        ('benches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPerfBench',
            fields=[
                ('bench_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benches.Bench')),
                ('duration', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=200)),
            ],
            bases=('benches.bench',),
        ),
        migrations.CreateModel(
            name='IPerfIntervalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalInSec', models.CharField(max_length=10)),
                ('transferredLastSecond', models.PositiveIntegerField()),
                ('globalBandwidth', models.PositiveIntegerField()),
                ('retransmittedLastSecond', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IPerfResult',
            fields=[
                ('result_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.Result')),
                ('total_retrans', models.PositiveIntegerField()),
                ('total_sent', models.PositiveIntegerField()),
            ],
            bases=('collect.result',),
        ),
        migrations.AddField(
            model_name='iperfintervalresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iperf.IPerfResult'),
        ),
    ]
