# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0006_benchmark_rcv_time'),
        ('iperf', '0002_auto_20180117_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPerfConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('port', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPerfInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalInSec', models.CharField(max_length=10)),
                ('transferredLastSecond', models.PositiveIntegerField()),
                ('globalBandwidth', models.PositiveIntegerField()),
                ('retransmittedLastSecond', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IPerfResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('total_retrans', models.PositiveIntegerField()),
                ('total_sent', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPerfTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('wait_time', models.DurationField()),
                ('duration', models.DurationField()),
                ('protocol', models.CharField(max_length=20)),
                ('protocol_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rcv_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptests.Benchmark')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='iperf.IPerfConfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='iperfresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='iperf.IPerfTest'),
        ),
        migrations.AddField(
            model_name='iperfinterval',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iperf.IPerfResult'),
        ),
        migrations.AlterUniqueTogether(
            name='iperftest',
            unique_together=set([('benchmark', 'order')]),
        ),
    ]
