# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iperf', '0004_iperfresult_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperftest',
            name='cell_bytes_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftest',
            name='cell_bytes_sent',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftest',
            name='wifi_bytes_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftest',
            name='wifi_bytes_sent',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
