# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iperf', '0006_iperftest_multipath_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperfconfig',
            name='download',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
