# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iperf', '0007_iperfconfig_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iperfinterval',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='iperf.IPerfResult'),
        ),
    ]
