# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplehttpget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleHttpGetResult',
            new_name='SimpleHttpGetOldResult',
        ),
    ]
