# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 15:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0004_auto_20180116_1535'),
        ('simplehttpget', '0002_auto_20180116_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleHttpGetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleHttpGetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleHttpGetTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('wait_time', models.DurationField()),
                ('duration', models.DurationField()),
                ('protocol', models.CharField(max_length=20)),
                ('protocol_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptests.Benchmark')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='simplehttpgetresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='simplehttpget.SimpleHttpGetTest'),
        ),
        migrations.AddField(
            model_name='simplehttpgetconfig',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='simplehttpget.SimpleHttpGetTest'),
        ),
        migrations.AlterUniqueTogether(
            name='simplehttpgettest',
            unique_together=set([('benchmark', 'order')]),
        ),
    ]
