# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplehttpget', '0007_auto_20180207_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplehttpgettest',
            name='multipath_service',
            field=models.CharField(default='aggregate', max_length=11),
            preserve_default=False,
        ),
    ]
