# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0002_benchmark_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('routable', models.BooleanField()),
                ('benchmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mptests.Benchmark')),
            ],
        ),
    ]
