# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0007_auto_20180117_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmark',
            old_name='model',
            new_name='device_model',
        ),
        migrations.RenameField(
            model_name='benchmark',
            old_name='model_code',
            new_name='device_model_code',
        ),
    ]
