# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0008_auto_20180118_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localisation',
            new_name='Location',
        ),
    ]
