# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0011_remove_benchmark_quic_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmark',
            name='ping_mean',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='ping_var',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='ping_med',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmark',
            name='ping_std',
            field=models.FloatField(default=1000.0),
            preserve_default=False,
        ),
    ]
