# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0012_auto_20180207_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmark',
            name='cell_bytes_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmark',
            name='cell_bytes_sent',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmark',
            name='wifi_bytes_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchmark',
            name='wifi_bytes_sent',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
