# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0014_benchmark_multipath_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_bytes_distance', models.FloatField()),
                ('wifi_bytes_lost_time', models.DateTimeField()),
                ('wifi_system_distance', models.FloatField()),
                ('wifi_system_lost_time', models.DateTimeField()),
                ('benchmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mptests.Benchmark')),
            ],
        ),
    ]
