# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0016_auto_20180214_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebenchmark',
            name='benchmark',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mptests.Benchmark'),
        ),
    ]
