# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0019_benchmark_user_interrupted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebenchmark',
            name='wifi_bssid_switches',
            field=models.IntegerField(default=0),
        ),
    ]
