# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0020_mobilebenchmark_wifi_bssid_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebenchmark',
            name='wifi_multiple_ssid',
            field=models.BooleanField(default=False),
        ),
    ]
