# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0001_initial'),
        ('benches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgBench',
            fields=[
                ('bench_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benches.Bench')),
                ('server_port', models.PositiveIntegerField()),
                ('query_size', models.PositiveIntegerField()),
                ('response_size', models.PositiveIntegerField()),
                ('start_delay_query_response', models.PositiveIntegerField()),
                ('nb_msgs', models.PositiveIntegerField()),
                ('interval_time_ms', models.PositiveIntegerField()),
                ('timeout_sec', models.PositiveIntegerField()),
            ],
            bases=('benches.bench',),
        ),
        migrations.CreateModel(
            name='MsgDelayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MsgResult',
            fields=[
                ('result_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.Result')),
                ('missed', models.PositiveIntegerField()),
            ],
            bases=('collect.result',),
        ),
        migrations.AddField(
            model_name='msgdelayresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.MsgResult'),
        ),
    ]
