# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 16:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mptests', '0004_auto_20180116_1535'),
        ('msg', '0002_auto_20180116_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=200)),
                ('query_size', models.PositiveIntegerField()),
                ('response_size', models.PositiveIntegerField()),
                ('start_delay_query_response', models.PositiveIntegerField()),
                ('nb_msgs', models.PositiveIntegerField()),
                ('interval_time_ms', models.PositiveIntegerField()),
                ('timeout_sec', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MsgDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MsgResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('missed', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MsgTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('wait_time', models.DurationField()),
                ('duration', models.DurationField()),
                ('protocol', models.CharField(max_length=20)),
                ('protocol_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mptests.Benchmark')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='msgresult',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='msg.MsgTest'),
        ),
        migrations.AddField(
            model_name='msgdelay',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg.MsgResult'),
        ),
        migrations.AddField(
            model_name='msgconfig',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='msg.MsgTest'),
        ),
        migrations.AlterUniqueTogether(
            name='msgtest',
            unique_together=set([('benchmark', 'order')]),
        ),
    ]
