# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quicinfos', '0001_initial'),
        ('msg', '0009_msgtest_mptcp_test_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgtest',
            name='quic_test_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quicinfos.QUICTestInfo'),
        ),
    ]
