# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('netconnectivities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('interface', models.CharField(choices=[('wifi', 'WiFi'), ('cell', 'Cellular')], max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='cellular_code',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='cellular_code_description',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='cellular_iso_country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='cellular_network_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='cellular_operator_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='network_type',
            field=models.CharField(choices=[('none', 'None'), ('wifi', 'WiFi'), ('cell', 'Cellular'), ('wificell', 'WiFi + Cellular')], default='none', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 11, 26, 28, 545159, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='wifi_bssid',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='netconnectivity',
            name='wifi_network_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='net_connectivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netconnectivities.NetConnectivity'),
        ),
    ]
