# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netconnectivities', '0002_auto_20180118_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netconnectivity',
            old_name='cellular_code',
            new_name='cell_code',
        ),
        migrations.RenameField(
            model_name='netconnectivity',
            old_name='cellular_code_description',
            new_name='cell_code_description',
        ),
        migrations.RenameField(
            model_name='netconnectivity',
            old_name='cellular_iso_country_code',
            new_name='cell_iso_country_code',
        ),
        migrations.RenameField(
            model_name='netconnectivity',
            old_name='cellular_network_name',
            new_name='cell_network_name',
        ),
        migrations.RenameField(
            model_name='netconnectivity',
            old_name='cellular_operator_code',
            new_name='cell_operator_code',
        ),
    ]
