# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netconnectivities', '0003_auto_20180118_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netconnectivity',
            name='network_type',
            field=models.CharField(choices=[('none', 'None'), ('wifi', 'WiFi'), ('cell', 'Cellular'), ('wificell', 'WiFi + Cellular'), ('cellwifi', 'Cellular + WiFi')], max_length=8),
        ),
    ]
