# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0001_initial'),
        ('benches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiriBench',
            fields=[
                ('bench_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benches.Bench')),
                ('server_port', models.PositiveIntegerField()),
                ('query_size', models.PositiveIntegerField()),
                ('response_size', models.PositiveIntegerField()),
                ('delay_query_response', models.PositiveIntegerField()),
                ('min_payload_size', models.PositiveIntegerField()),
                ('max_payload_size', models.PositiveIntegerField()),
                ('interval_time_ms', models.PositiveIntegerField()),
                ('nb_packets_bursts', models.PositiveIntegerField()),
                ('time_between_bursts_ms', models.PositiveIntegerField()),
                ('time_test_ms', models.PositiveIntegerField()),
            ],
            bases=('benches.bench',),
        ),
        migrations.CreateModel(
            name='SiriDelayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SiriResult',
            fields=[
                ('result_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.Result')),
                ('missed', models.PositiveIntegerField()),
            ],
            bases=('collect.result',),
        ),
        migrations.AddField(
            model_name='siridelayresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siri.SiriResult'),
        ),
    ]
