# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect', '0001_initial'),
        ('benches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeStreamingBench',
            fields=[
                ('bench_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benches.Bench')),
                ('video_id', models.CharField(max_length=30)),
                ('video_type', models.CharField(max_length=8)),
                ('duration', models.PositiveIntegerField()),
                ('video_itag', models.PositiveSmallIntegerField()),
                ('video_framerate', models.PositiveSmallIntegerField()),
                ('video_codec', models.CharField(max_length=50)),
                ('video_size', models.CharField(max_length=11)),
                ('video_quality', models.CharField(max_length=6)),
                ('video_vquality', models.CharField(max_length=6)),
                ('video_url', models.CharField(max_length=100)),
                ('video_bytes_rate', models.PositiveIntegerField()),
                ('audio_itag', models.PositiveSmallIntegerField()),
                ('audio_bitrate', models.PositiveIntegerField()),
                ('audio_codec', models.CharField(max_length=50)),
                ('audio_url', models.CharField(max_length=100)),
                ('audio_bytes_rate', models.PositiveIntegerField()),
                ('playout_buffer_sec', models.PositiveSmallIntegerField()),
                ('maxtime', models.PositiveSmallIntegerField()),
            ],
            bases=('benches.bench',),
        ),
        migrations.CreateModel(
            name='YoutubeStreamingResult',
            fields=[
                ('result_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.Result')),
                ('result', models.CharField(max_length=4)),
                ('download_time', models.DurationField()),
                ('nb_stalls', models.PositiveSmallIntegerField()),
                ('avg_stall_duration', models.DurationField()),
                ('total_stall_time', models.DurationField()),
                ('initial_prebuf_time', models.DurationField()),
                ('video_download_rate', models.PositiveIntegerField()),
                ('video_total_bytes', models.PositiveIntegerField()),
                ('video_download_time', models.DurationField()),
                ('video_cdn_ip', models.GenericIPAddressField()),
                ('video_conn_time', models.DurationField()),
                ('video_bitrate_iqr', models.PositiveIntegerField()),
                ('audio_download_rate', models.PositiveIntegerField()),
                ('audio_total_bytes', models.PositiveIntegerField()),
                ('audio_download_time', models.DurationField()),
                ('audio_cdn_ip', models.GenericIPAddressField()),
                ('audio_conn_time', models.DurationField()),
                ('first_conn_time', models.DurationField()),
                ('startup_time', models.DurationField()),
                ('max_bytes_rate', models.PositiveIntegerField()),
                ('error_code', models.PositiveSmallIntegerField()),
                ('error_msg', models.CharField(max_length=28)),
            ],
            bases=('collect.result',),
        ),
    ]
